[package]
name = "bulletproofs-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "=0.5.0"
ark-test-curves = "0.5.0"
ark-std = "0.5.0"
ark-bls12-381 = "0.5.0"
ark-poly = "0.5.0"
ark-ec = "0.5.0"
rand = "0.8.5"
num-bigint = "0.4.6"
blake3 = "1.5"
ark-bn254 = "0.5.0"
sha256 = "1.5.0"
